### ISSUE TITLE
Can't use Statement.returnGeneratedValues() with INSERT .. SELECT

### ISSUE THREAD

**Issue by lukaseder** [oracle/oracle-r2dbc#18]
This is perfectly valid Oracle SQL:

```sql
create table t (id number generated always as identity primary key, val number);
insert into t (val) select 1 from dual union all select 2 from dual;
```

But when I try to run the `INSERT .. SELECT` statement with r2dbc trying to fetch the generated identity values:

```java
System.out.println((
    Flux.from(connectionFactory.create())
        .flatMap(c -> c
            .createStatement("insert into t (val) select 1 from dual union all select 2 from dual")
            .returnGeneratedValues("id")
            .execute())
        .flatMap(it -> it.map((r, m) -> r.get(0)))
        .collectList()
        .block().get(0)
));
```

Then I'm getting the following errors:

```
Exception in thread "main" io.r2dbc.spi.R2dbcBadGrammarException: [933] [42000] ORA-00933: SQL-Befehl wurde nicht korrekt beendet

	at oracle.r2dbc.impl.OracleR2dbcExceptions.toR2dbcException(OracleR2dbcExceptions.java:162)
	at reactor.core.publisher.Flux.lambda$onErrorMap$29(Flux.java:6670)
	at reactor.core.publisher.Flux.lambda$onErrorResume$30(Flux.java:6723)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at org.reactivestreams.FlowAdapters$FlowToReactiveSubscriber.onError(FlowAdapters.java:223)
	at oracle.jdbc.internal.CompletionStageUtil$BatchItemPublisher.subscribeToFailedBatch(CompletionStageUtil.java:544)
	at oracle.jdbc.internal.CompletionStageUtil$BatchItemPublisher.lambda$subscribe$0(CompletionStageUtil.java:507)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at oracle.jdbc.driver.PhysicalConnection.lambda$createUserCodeExecutor$10(PhysicalConnection.java:11713)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at oracle.jdbc.driver.PhysicalConnection.lambda$createUserCodeExecutor$11(PhysicalConnection.java:11711)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at org.jooq.testscripts.R2DBC.main(R2DBC.java:35)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL-Befehl wurde nicht korrekt beendet

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:628)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:562)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1207)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:727)
	at oracle.jdbc.driver.T4CTTIfun.lambda$receiveRPCAsync$2(T4CTTIfun.java:426)
	at oracle.jdbc.internal.CompletionStageUtil.handleNormalCompletion(CompletionStageUtil.java:176)
	at oracle.jdbc.internal.CompletionStageUtil.lambda$normalCompletionHandler$1(CompletionStageUtil.java:227)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at oracle.jdbc.driver.T4CTTIfun.lambda$receiveRPCAsync$0(T4CTTIfun.java:406)
	at oracle.jdbc.driver.RestrictedLock.lambda$runUnrestricted$0(RestrictedLock.java:253)
	at oracle.jdbc.driver.RestrictedLock.callUnrestricted(RestrictedLock.java:273)
	at oracle.jdbc.driver.RestrictedLock.runUnrestricted(RestrictedLock.java:252)
	at oracle.jdbc.driver.PhysicalConnection.lambda$createInternalCodeExecutor$7(PhysicalConnection.java:11647)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at oracle.jdbc.driver.PhysicalConnection.lambda$createInternalCodeExecutor$8(PhysicalConnection.java:11644)
	... 6 more
Caused by: Error : 933, Position : 78, Sql = insert into t (val) select 1 from dual union all select 2 from dual RETURNING id INTO :1 , OriginalSql = insert into t (val) select 1 from dual union all select 2 from dual RETURNING id INTO ?, Error Msg = ORA-00933: SQL-Befehl wurde nicht korrekt beendet

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:632)
	... 22 more
```

**Comment by Michael-A-McMahon** [comment]
Thanks for this.

When returning generated values with Oracle Database, we can only support cases where a "RETURNING INTO" clause would be valid. That is, if the SQL command input to Oracle R2DBC/JDBC could be rewritten to include a RETURNING INTO clause, then we can support it.
I do want to mention that better support for generated values is something that the Oracle JDBC Team is looking into, and we might see some limitations lifted in the future. I can't promise anything at this time.

So there is definitely a documentation bug here; I need to update the README to specify which SQL commands are supported with returnGeneratedValues(String...)
For this case, the INSERT command includes a subquery expression, and I don't think we can have a RETURNING INTO clause when a subquery is present (I will verify this today). But for now, going off the Oracle Database SQL Reference, it seems that we can't use RETURNING INTO with subqueries:
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/INSERT.html#GUID-903F8043-0254-4EE9-ACC1-CB8AC0AF3423

**Comment by lukaseder** [comment]
Right, I thought we could emulate this on the jOOQ side, but we can't in fact. We can emulate multi-row `INSERT .. RETURNING` (which Oracle currently doesn't support natively) using an anonymous  block with `FORALL .. INSERT .. BULK COLLECT INTO` and a bunch of ref cursor out parameters. But `INSERT .. SELECT .. RETURNING` is harder.

I'm just now thinking to emulate this with a `SELECT .. BULK COLLECT INTO` and then again `FORALL .. INSERT .. BULK COLLECT INTO`. That may be something the JDBC team could consider... Or, the SQL team could enhance the syntax to work more like Db2's `FINAL TABLE` or PostgreSQL's `RETURNING`? But that's out of scope for this issue here.

Is there any way to produce a better error message? I didn't even see the synthetic `RETURNING` clause that had been added.

**Comment by Michael-A-McMahon** [comment]
I'll give some thought about how to improve the error message. It would certainly be helpful to draw attention to the fact that Oracle JDBC has generated a RETURNING INTO clause.

Oracle R2DBC does not currently support out-bind registration, as in CallableStatement.registerOutParameter(int, SQLType), or OraclePreparedStatement.registerReturnParameter(int, int). This is going to prevent jOOQ and other consumers from executing SQL using out-binds, such as RETURNING INTO.
Oracle R2DBC is currently implementing v0.8.2 of the R2DBC SPI, we need to update it to 0.9.x in order to support out-binds with io.r2dbc.spi.Parameter (this SPI was not added until 0.9).

I think I can get going on the 0.9 SPI update this week.

**Comment by lukaseder** [comment]
Interesting, that's good to know. Also `dbms_sql.return_result(...)` doesn't seem to work yet as a workaround. Indeed, jOOQ relies on both of these mechanisms heavily for a lot of the more advanced use-cases. Will be keeping an eye out for the next version, then.
