### ISSUE TITLE
java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Integer

### ISSUE THREAD

**Issue by dpavanelli** [oracle/oracle-r2dbc#26]
I'm still working on some tests with this driver, and whenever I need to read a numeric value from result set and cast it to Int like below:

 ```kotlin
     return r2dbcTemplate
                .databaseClient
                .sql("select count(1) as total_orders from orders")
                .fetch()
                .one()
                .flatMap { row ->
                    Mono.just(row["total_orders"] as Int)
                }
```
I'm getting this error:

``` Kotlin
 java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Integer (java.math.BigDecimal and java.lang.Integer are in module java.base of loader 'bootstrap')
        ...
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmitScalar(FluxFlatMap.java:488) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:421) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onComplete(FluxBuffer.java:185) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2057) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredComplete(FluxUsingWhen.java:405) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:540) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2057) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2057) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators$MonoSubscriber.onComplete(Operators.java:1857) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onComplete(MonoIgnoreThen.java:323) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators$MonoSubscriber.onComplete(Operators.java:1857) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onComplete(MonoIgnoreThen.java:323) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:678) ~[reactor-pool-0.2.3.jar!/:0.2.3]
 	at reactor.core.publisher.Operators.complete(Operators.java:136) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:790) ~[reactor-pool-0.2.3.jar!/:0.2.3]
 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:83) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:157) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onError(FluxFilter.java:291) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:259) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators.error(Operators.java:197) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:397) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:894) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:997) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2057) ~[reactor-core-3.4.4.jar!/:3.4.4]
 	at org.reactivestreams.FlowAdapters$FlowToReactiveSubscriber.onComplete(FlowAdapters.java:228) ~[reactive-streams-1.0.3.jar!/:na]
 	at oracle.jdbc.driver.PhasedPublisher$PhasedSubscription.emitComplete(PhasedPublisher.java:434) ~[ojdbc11-21.1.0.0.jar!/:21.1.0.0.0]
 	at oracle.jdbc.driver.PhasedPublisher.lambda$subscribe$3(PhasedPublisher.java:343) ~[ojdbc11-21.1.0.0.jar!/:21.1.0.0.0]
 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
 	at oracle.jdbc.driver.PhysicalConnection.lambda$createUserCodeExecutor$10(PhysicalConnection.java:11713) ~[ojdbc11-21.1.0.0.jar!/:21.1.0.0.0]
 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) ~[na:na]
 	at oracle.jdbc.driver.PhysicalConnection.lambda$createUserCodeExecutor$11(PhysicalConnection.java:11711) ~[ojdbc11-21.1.0.0.jar!/:21.1.0.0.0]
 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429) ~[na:na]
 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

```

Off course, it is possible to use BigDecimal for any numeric value (and then converting it to Int/Long, etc), but I don't know if this is some compatibility error between spring/ojdbc11/oracle-r2dbc, or something expected at this moment.

Are other numeric types (besides BigDecimal) supported already?

**Comment by mp911de** [comment]
To let the driver perform type conversion, you need to pass in the target type. Update `row["total_orders"]` to `row["total_orders", Int::class.javaObjectType]`.

**Comment by dpavanelli** [comment]
Thanks @mp911de, didn't know that!

**Comment by Michael-A-McMahon** [comment]
@dpavanelli: I strongly encourage using Row.get(int/String, Class) over Row.get(int/String). Providing the Class argument will provide type safety at compile time for your code. Oracle R2DBC leverages Oracle JDBC's type converter, so we support a wide variety of SQL to Java type conversions.
